version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
volumes:
  db:
    driver: local
